feat: ✨ Add maps to event layout
octree-gva/caroster pull request #26
Opened 2023-09-27 10:41 UTC by SimonMulquin

- Updated events model with coordinates in Strapi
- Updated travels model with meeting coordinates in Strapi
- Added a map on the event details
- Updated event details ui
- Added a map on the event travels list
- Updated drawer ui
- Updated event's top bar ui

In order to display the maps, please manually add coordinates in Strapi content manager on both the event and one of the associated travels.

The current ui supports the absence of coordinates, map won't be displayed if there is no geographic data to show.

2023-09-29 14:26 UTC, 5ika requested changes
@SimonMulquin Ça fonctionne bien :+1:  J'ai fait quelques retours sur la qualité de code mais ça va être vite mergé.

2023-09-29 14:26 UTC, 5ika commented on frontend/containers/TravelColumns/index.tsx
> +  });
@SimonMulquin C'est bizarre d'avoir un `forEach` et faire des `push` dans un tableau. Cela correspond à deux méthodes de programmation (fonctionnelle ou séquentielle).
Ici, pour faire plus court et plus clair, tu peux éventuellement faire un map + filter ou même un reduce.

2023-09-29 14:26 UTC, 5ika commented on frontend/pages/api/mapbox/geocoding.ts
> +  console.log({search, proximity});
@SimonMulquin Console.log à retirer

2023-09-29 14:26 UTC, 5ika commented on frontend/containers/Map/Map.tsx
> +const DEV_TILES_URL = process.env.DEV_TILES_URL;
@SimonMulquin Il peut être pratique de mettre une valeur par défaut ici pour limiter le nombre de configuration.

2023-10-02 14:27 UTC, SimonMulquin commented
@5ika  thanks for the feedback :-)

For the default value of the const DEV_TILES_URL, I put it but it should be replaced in favor of a format supporting not only tile.openstreetmap.org but other third parties  APIs such as Mapbox, without compromising the token they require.

The risk of a too simple configuration here is that the installer might not be aware that the use of tile.openstreetmap.org API on a production instance is contrary to the OSM T&Cs and can harm both their operations and OSM's.

https://operations.osmfoundation.org/policies/tiles/

2023-10-02 15:17 UTC, merged